### ISSUE TITLE
Navegadores com chromium engine 

### ISSUE THREAD

**Issue by codigocarvalho** [CachopaWeb/horse-server-static#1]
Estou testando esse middleware, fiz uma aplicação com react, no firefox funciona perfeitamente, em navegadores chromium não carrega os arquivos de estilização (css) corretamente, testei no edge, chrome, opera. Testei com o apache, funciona em todos navegadores.

**Comment by cachopaweb** [comment]
Realmente testei com um site feito em flutter e funcionou bem, mas não era algo grande. 
Mas vou continuar evoluindo ele para servir mais conteúdos não apenas imagens estáticas que foi o intuito inicial de desenvolvê-lo. 
Obrigado pela atenção...

**Comment by codigocarvalho** [comment]
Muito obrigado pela atenção e pelo projeto
