### ISSUE TITLE
Servidor Fechando ao abrir um arquivo estático

### ISSUE THREAD

**Issue by FABIOMATTE** [CachopaWeb/horse-server-static#5]
Boa Tarde,

Dentro da unit Horse.ServerStatic, na linha especifica da imagem abaixo, tive que passar a variável **Path**, para que o ServerStatic entendesse a rota corretamente, porém, no Horse 3.1.0, após abrir um arquivo Estático, o servidor acaba fechado sozinho.
![image](https://user-images.githubusercontent.com/999181/225133623-9c6098b2-b878-448a-a42c-1882b57e7336.png)

E não consegui descobrir uma forma de contornar esse erro.

**Comment by cachopaweb** [comment]
Bom dia,
Como vc registrou a pasta onde está os arquivos estáticos?
THorse.Use(ServerStatic('public'));
No caso public é a pasta onde estão os arquivos...

**Comment by FABIOMATTE** [comment]
> Bom dia, Como vc registrou a pasta onde está os arquivos estáticos? THorse.Use(ServerStatic('public')); No caso public é a pasta onde estão os arquivos...

Bom dia amigo, sim, exatamente isso, porem passando de forma dinamica, ao final do bloco:

```

  THorse.Use(CORS)
        .Use(HorseBasicAuthentication(onAuth, THorseBasicAuthenticationConfig.New.SkipRoutes(['/'])))
        .Use(OctetStream)
        .Use(Compression)
        .Use(Jhonson)
        .Use(HandleException)
        .Use(ServerStatic(gClienteLogos)); // <<<<<<<<<< CODIGO PARA PASTA FISICA 

    TBase.Router;
    TLogin.Router;

    {$ifdef horse_cgi}
    THorse.Listen;
    {$else}
      THorse.Listen( SrvPort , onListen);
    {$endif}
```

**Comment by cachopaweb** [comment]
.Use(HorseBasicAuthentication(onAuth, THorseBasicAuthenticationConfig.New.SkipRoutes(['/'])))

Será que essa linha não esta dando conflito? Pois ela irá exigir autenticação... Tenta comentá-la e testar para ver...
