### ISSUE TITLE
Erro ao atualizar a ultima versão do Horse

### ISSUE THREAD

**Issue by vipeol** [CachopaWeb/horse-server-static#6]
Olá,

  Ao executar o boss update, passou a aparecer os erros abaixo, preciso fazer algo ou é realmente um bug?

[dcc32 Error] Horse.ServerStatic.pas(50): E2003 Undeclared identifier: 'TKind'
[dcc32 Error] Horse.ServerStatic.pas(103): E2003 Undeclared identifier: 'Default'

Obrigado!

**Comment by cachopaweb** [comment]
Olá, vc usa o Delphi ou Lazarus?

**Comment by vipeol** [comment]
Estou usando o Delphi

**Comment by cachopaweb** [comment]
Vou verificar se foi introduzido algum bug na última versão... Aguarde por favor...

**Comment by cachopaweb** [comment]
Olá, amigo fiz uns testes aqui e não encontrei erros no middleware. 
Verifica se vc esta usando a última versão do middleware, fazendo favor... 
Se não tiver da o comando: boss update

**Comment by vipeol** [comment]
Estranho,

  Fiz exatamente isto, havia muito tempo que não atualizava, hoje dei o comando boss update e o erro apareceu, veja que ao clicar no TMimeTypes o delphi abre o arquivo Horse.Commons, que realmente nao possui o tipo TKind

![image](https://github.com/cachopaweb/horse-server-static/assets/20286865/fcca559c-8d2f-4a72-8830-17b6f1d3d4d6)
![image](https://github.com/cachopaweb/horse-server-static/assets/20286865/13361d19-2d7f-462a-91af-d39b44e503fb)

**Comment by cachopaweb** [comment]
Aqui no meu Delphi esta normal. 
![Captura de tela 2023-06-21 160544](https://github.com/cachopaweb/horse-server-static/assets/46660852/ab09d6c6-7348-4341-9925-c4889adb6bc6)
Verifica se no seu tem essa uses:
System.Net.Mime

Essa dependência vem desta unit;

**Comment by vipeol** [comment]
Acho que o delphi esta batendo cabeça com os uses, o seu esta diferente do meu. 

![image](https://github.com/cachopaweb/horse-server-static/assets/20286865/18dccde2-a212-4e2a-877c-5206dbe3aa55)

**Comment by cachopaweb** [comment]
Estranho, que tá bem parecido...
![Captura de tela 2023-06-21 162223](https://github.com/cachopaweb/horse-server-static/assets/46660852/a487df26-9510-4529-96c8-828294454747)

**Comment by cachopaweb** [comment]
Creio que o seu Delphi perdeu alguma, path, verifica no seu Library Paths....

**Comment by vipeol** [comment]
Realmente esta igual, não havia percebido o corte na imagem anterior sua da parte do uses de cima...
No meu quando eu clico com o ctrl+clique sobre o TKind esta me jogando para dentro da unit HORSE.Commons, e não para aquela que me falou

**Comment by cachopaweb** [comment]
No meu as vezes dá esses bugs, dai resolvo rebuildando todo o projeto assim...
![Captura de tela 2023-06-21 162521](https://github.com/cachopaweb/horse-server-static/assets/46660852/b89ec8aa-9acc-4736-843a-18114cfde943)

**Comment by vipeol** [comment]
Esta System.Net.Mime minha tambem nao tem este tipo TKind

![image](https://github.com/cachopaweb/horse-server-static/assets/20286865/3ecb5d16-3510-4732-9d80-84f198bbb1ef)

**Comment by vipeol** [comment]
Eu já fiz o Clean Project e o Build All tambem antes para testar...

**Comment by cachopaweb** [comment]
Procura pela classe TMineTypes, tem que existir, alias que versão é teu Delphi?
![Captura de tela 2023-06-21 162958](https://github.com/cachopaweb/horse-server-static/assets/46660852/67541933-1a9c-4ca7-b2fd-7be6ad6a9eaa)

**Comment by vipeol** [comment]
Já procurei na unit System.Net.Mime não tem a classe, meu delphi é o Berlim 10.1

**Comment by cachopaweb** [comment]
Hum, vai ser a versão do Delphi então heim, o meu é Tokio 10.2. Descobrimos...

**Comment by vipeol** [comment]
Lascou, então... rsrsrs

**Comment by cachopaweb** [comment]
Ou vc usa a versão antiga do middleware ou um Delphi mais novo rsrs

**Comment by vipeol** [comment]
vou tentar voltar a versão do middleware

**Comment by cachopaweb** [comment]
Apaga a pasta modules, e edita seu boss.json e deixa a versão do middleware que vc usava antes e dá um: boss install no seu projeto que ele deve manter a antiga.

**Comment by cachopaweb** [comment]
> vou tentar voltar a versão do middleware

Isso...

**Comment by vipeol** [comment]
Valeu, vou tentar aqui. Obrigado!

**Comment by cachopaweb** [comment]
Opa disponha, até mais...
